apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "zigbee2mqtt.fullname" .) }}
data:
  configuration.yaml: |
    {{- toYaml .Values.zigbee2mqtt.initConfig | nindent 4 -}}
