apiVersion: v1
kind: Service
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zigbee2mqtt.service.type }}
  selector:
    {{- include "zigbee2mqtt.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.zigbee2mqtt.service.port }}
      targetPort: http
