apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zigbee2mqtt.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "zigbee2mqtt.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "zigbee2mqtt.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init
          image: busybox
          command: ["sh"]
          args:
            - -c
            - "{{- if .Values.zigbee2mqtt.overwriteConfig -}}cp /configuration.yaml /app/data/{{- else -}}[ -f /app/data/configuration.yaml ] || cp /configuration.yaml /app/data/{{- end -}}"
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: config
              mountPath: /configuration.yaml
              subPath: configuration.yaml
      containers:
        - name: app
          securityContext:
            privileged: true
          image: "{{ .Values.zigbee2mqtt.image }}"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: udev
              mountPath: /run/udev
              readOnly: true
            - name: zigbee-device
              mountPath: /dev/ttyUSB0
          env:
            - name: TZ
              value: "{{ .Values.zigbee2mqtt.config.TZ }}"
      volumes:
        - name: udev
          hostPath:
            path: /run/udev
            type: Directory
        - name: zigbee-device
          hostPath:
            path: "{{ .Values.zigbee2mqtt.config.zigbee_device }}"
        - name: config
          configMap:
            name: {{ printf "%s-config" (include "zigbee2mqtt.fullname" .) }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
