zigbee2mqtt:
  image: koenkk/zigbee2mqtt:2.6.3
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: zigbee2mqtt.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  config:
    TZ: "Europe/Berlin"
    zigbee_device: /dev/ttyUSB0

  overwriteConfig: false
  initConfig:
    homeassistant: true
    permit_join: true
    frontend: true
    mqtt:
      base_topic: zigbee2mqtt
      server: "mqtt://mosquitto"
      include_device_information: true
    serial:
      port: /dev/ttyUSB0
    advanced:
      network_key: GENERATE
      log_output:
        - console
      log_level: info
      last_seen: "ISO_8601"
      homeassistant_discovery_topic: "homeassistant"
      homeassistant_status_topic: "homeassistant/status"
