zigbee2mqtt:
  image:
    repository: koenkk/zigbee2mqtt
    tag: "" # defaults to .Chart.AppVersion when empty
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: zigbee2mqtt.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  timezone: "Europe/Berlin"
  zigbee_device: /dev/ttyUSB0

  overwriteConfig: false
  initConfig:
    homeassistant:
      enabled: true
      discovery_topic: homeassistant
      status_topic: homeassistant/status
    permit_join: true
    frontend:
      enabled: true
    mqtt:
      base_topic: zigbee2mqtt
      server: "mqtt://mosquitto"
      include_device_information: true
    serial:
      port: /dev/ttyUSB0
    advanced:
      log_output:
        - console
      log_level: info
      last_seen: "ISO_8601"
