name: Release Charts

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: Generate changelog
        id: changelog
        run: |
          tag="${GITHUB_REF_NAME}"

          printf 'changelog<<EOF\n' >> "$GITHUB_OUTPUT"
          git cliff --unreleased --tag "${tag}" >> "$GITHUB_OUTPUT"
          printf 'EOF\n' >> "$GITHUB_OUTPUT"

      - name: Package Helm chart
        id: package
        run: |
          mkdir -p dist
          helm package charts/zigbee2mqtt --destination dist
          file=$(ls dist/zigbee2mqtt-*.tgz)
          echo "file=$file" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: ${{ steps.package.outputs.file }}
          make_latest: true

  update-registry:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: 2336325
          private-key: ${{ secrets.UPDATE_REGISTRY_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Trigger registry update
        uses: the-actions-org/workflow-dispatch@v4
        with:
          repo: "ammarlakis/helm-charts"
          workflow: Add Chart to Helm Repository
          ref: "master"
          wait-for-completion: false
          inputs: |
            {
              "repository": "${{ github.repository }}",
              "release_name": "${{ github.ref_name }}"
            }
          token: ${{ steps.app-token.outputs.token }}
